[run]
  timeout = "1m"

[linters]
  enable = ['bodyclose', 'cyclop', 'dupl', 'errorlint', 'gochecknoinits', 'gocognit', 'goconst', 'gocritic', 'gocyclo',
            'goimports', 'golint', 'gosec', 'nakedret', 'unconvert', 'unparam']

[linters-settings]
  [linters-settings.dupl]
    threshold = 100
  [linters-settings.errcheck]
    check-type-assertions = true
    check-blank = true
  [linters-settings.gocognit]
    min-complexity = 10
  [linters-settings.gocyclo]
    min-complexity = 10
  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 4.0
